// FILE: src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/dashboard/SideBar";
import Topbar from "@/components/dashboard/TopBar";
import Breadcrumbs from "@/components/navigation/Breadcrumbs";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100svh] overflow-hidden bg-background text-foreground`}>
        <div className="flex h-[100svh]">
            <Sidebar />
            <div className="flex min-h-0 flex-1 flex-col">
                <Topbar />
                {/* Only MAIN scrolls */}
                <main className="min-h-0 flex-1 overflow-auto">
                    <div className="mx-auto max-w-[1400px] p-4 md:p-6">
                        {/* Breadcrumbs show automatically on subpages; hidden on top-level */}
                        <Breadcrumbs hideOn={["/"]} className="mb-3" />
                        {children}
                    </div>
                </main>
            </div>
        </div>
        </body>
        </html>
    );
}
